local u

u = BuildingAndHeroDefinition:new("aa00", "ewsp")
u:setAllowCustomTeamColor(true)
u:setAnimationCastBackswing(0.0)
u:setArtSpecial("")
u:setCanFlee(false)
u:setCollisionSize(0.0)
u:setDeathTimeseconds(0.001)
u:setElevationSampleRadius(0.0)
u:setFoodCost(0)
u:setHasWaterShadow(false)
u:setHitPointsMaximumBase(500000)
u:setManaInitialAmount(100000)
u:setManaMaximum(100000)
u:setMaximumPitchAngledegrees(0.0)
u:setMaximumRollAngledegrees(0.0)
u:setMovementType("")
u:setNormalAbilities("Avul,Aloc")
u:setSightRadiusDay(0)
u:setSightRadiusNight(0)
u:setSpeedBase(0)
u:setStructuresBuilt("")
u:setTargetedAs("invulnerable")
u:setTurnRate(3.0)
u:setUnitClassification("")
u:setUnitSoundSet("")
u:setUpgradesUsed("")

u = BuildingAndHeroDefinition:new("aa01", "ewsp")
u:setAllowCustomTeamColor(true)
u:setAnimationCastBackswing(0.0)
u:setArtSpecial("")
u:setCanFlee(false)
u:setCollisionSize(0.0)
u:setDeathTimeseconds(0.001)
u:setElevationSampleRadius(0.0)
u:setFoodCost(0)
u:setHasWaterShadow(true)
u:setHitPointsMaximumBase(500000)
u:setManaInitialAmount(100000)
u:setManaMaximum(100000)
u:setMaximumPitchAngledegrees(0.0)
u:setMaximumRollAngledegrees(0.0)
u:setMovementType("")
u:setNormalAbilities("")
u:setScalingValue(0.001)
u:setSelectionScale(-1.0)
u:setSightRadiusDay(0)
u:setSightRadiusNight(0)
u:setSpeedBase(0)
u:setStructuresBuilt("")
u:setTeamColor(12)
u:setTurnRate(3.0)
u:setUnitClassification("")
u:setUnitSoundSet("")
u:setUpgradesUsed("")
