OnInit.trig(function()
    local DUMMY_ID = FourCC(UID.CASTER_DUMMY)
    local CAST_SPELL = FourCC(AID.ARMY_OF_NATURE)
    local CO_SPELL = FourCC(AID.ARMY_OF_NATURE_CO_SUMMON)

    RegisterSpellEffectEvent(CAST_SPELL, function()
        local c = GetTriggerUnit()
        local x, y = GetUnitX(c), GetUnitY(c)
        local dummy = CreateUnit(GetOwningPlayer(GetTriggerUnit()), DUMMY_ID, x, y, GetUnitFacing(c))
        ShowUnit(dummy, false)
        UnitApplyTimedLife(dummy, 1, 1)
        UnitAddAbility(dummy, CO_SPELL)
        SetUnitAbilityLevel(dummy, CO_SPELL, GetUnitAbilityLevel(GetTriggerUnit(), CAST_SPELL))
        IssueImmediateOrder(dummy, "waterelemental")
    end)
end)
