OnInit.trig(function()
    local DUMMY_ID = FourCC(UID.CASTER_DUMMY)
    local CAST_SPELL = FourCC(AID.PROTECTION_OF_NATURE)
    local IMPL_SPELL = FourCC(AID.PROTECTION_OF_NATURE_IMPL)

    RegisterSpellEffectEvent(CAST_SPELL, function()
        local u = GetSpellTargetUnit()
        local x, y = GetUnitX(u), GetUnitY(u)
        local dummy = CreateUnit(GetOwningPlayer(GetTriggerUnit()), DUMMY_ID, x, y, 0)
        ShowUnit(dummy, false)
        UnitApplyTimedLife(dummy, 1, 1)
        UnitAddAbility(dummy, IMPL_SPELL)
        SetUnitAbilityLevel(dummy, IMPL_SPELL, GetUnitAbilityLevel(GetTriggerUnit(), CAST_SPELL))
        IssueTargetOrder(dummy, "innerfire", u)
    end)
end)
