dofile("lib/debug_utils/init.lua")
dofile("lib/influa/timed.lua")
dofile("lib/influa/total_initialization.lua")
dofile("lib/new_bonus.lua") -- requires Total Initialization
dofile("lib/player_unit_event.lua")
dofile("lib/spell_effect_event.lua")
dofile("lib/synced_table.lua")

dofile("utils/ability.lua")
dofile("utils/coordinate.lua")
dofile("utils/destructible.lua")
dofile("utils/group.lua")
dofile("utils/unit.lua")

dofile("ids.lua")
dofile("test.lua")
dofile("testmap.lua")

dofile("melee/ai_surrender.lua")
dofile("melee/automine.lua")
dofile("melee/disable_melee_heroes.lua")
dofile("melee/fov.lua")
dofile("melee/handicap.lua")
dofile("melee/hero_limit.lua")
dofile("melee/player_leave.lua")

dofile("skills/ancient_incarnation.lua")
dofile("skills/area_holy_light.lua")
dofile("skills/army_of_nature.lua")
dofile("skills/blood_elemental.lua")
dofile("skills/frost_blast.lua")
dofile("skills/kings_stride_aura.lua")
dofile("skills/mana_ward.lua")
dofile("skills/mass_banish.lua")
dofile("skills/mass_entangling_roots.lua")
dofile("skills/mass_recall.lua")
dofile("skills/nature_affinity.lua")
dofile("skills/plot_armor.lua")
dofile("skills/protection_of_nature.lua")
dofile("skills/resonating_blade.lua")
dofile("skills/spiritual_fire_ball.lua")
